# Generated by Django 4.0.6 on 2022-07-17 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_auction_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='bid',
            field=models.IntegerField(default=0),
        ),
    ]
